# Generated by Django 4.2.6 on 2023-12-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='collected_sent',
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
